steps:
  # Deploy Airflow DAGs
  - name: "gcr.io/cloud-builders/gsutil"
    id: "Deploy Airflow DAGs"
    args:
      [
        "rsync",
        "-r",
        "-d",
        "-x",
        "'.*\\.git.*'",
        "airflow/dags",
        "gs://${_COMPOSER_BUCKET}/dags",
      ]
    waitFor: ["-"]

  # Deploy Airflow plugins
  - name: "gcr.io/cloud-builders/gsutil"
    id: "Deploy Airflow plugins"
    args:
      [
        "rsync",
        "-r",
        "-d",
        "-x",
        "'.*\\.git.*'",
        "airflow/plugins",
        "gs://${_COMPOSER_BUCKET}/plugins",
      ]
    waitFor: ["-"]

  # Deploy pubsub-to-firestore cloud function
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy pubsub-to-firestore function"
    args:
      [
        "functions",
        "deploy",
        "pubsub-to-firestore",
        "--entry-point",
        "PubSubConsumer",
        "--runtime",
        "go111",
        "--trigger-topic",
        "${_PUBSUB_TOPIC}",
      ]
    dir: "function"
    waitFor: ["-"]

  # Deploy front-end
  - name: "gcr.io/cloud-builders/npm"
    id: "Install frontend dependencies"
    args: ["install"]
    dir: "frontend"
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/npm"
    id: "Build frontend"
    args: ["run", "build"]
    dir: "frontend"
    waitFor:
      - "Install frontend dependencies"
  - name: "gcr.io/$PROJECT_ID/firebase"
    id: "Deploy frontend"
    args: ["deploy", "--project", "${_FRONTEND_PROJECT}", "--only", "hosting"]
    dir: "frontend"
    waitFor:
      - "Build frontend"
substitutions:
  _COMPOSER_BUCKET: asia-northeast1-composer-de-4c077a35-bucket
  _PUBSUB_TOPIC: composer-demo
  _FRONTEND_PROJECT: servian-chris-sandbox
