steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "rsync",
        "-r",
        "-d",
        "-x",
        "'.*\\.git.*'",
        "airflow/dags",
        "gs://asia-northeast1-composer-de-4c077a35-bucket/dags",
      ]
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "rsync",
        "-r",
        "-d",
        "-x",
        "'.*\\.git.*'",
        "airflow/plugins",
        "gs://asia-northeast1-composer-de-4c077a35-bucket/plugins",
      ]
