steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "rsync",
        "-r",
        "-x",
        "'.*\\.git.*''",
        "airflow",
        "gs://asia-northeast1-composer-de-4c077a35-bucket",
      ]
